name: Demo Github Actions Events
run-name: Demo GitHub Actions Events

on:
  # Webhook events
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: [main]
  issues:
    types: 
      - opened
      - closed
  
  # Scheduled events
  schedule:
    - cron: 0 9 * * *
    - cron: 0 12 * * 0

  # Manual events
  workflow_dispatch: 
    inputs:
      yourName:
        description: What's your name?
        required: true
        default: My friend
      feelingGood:
        description: Are you feeling good?
        required: true
        type: boolean
      howYouFindGitHubActions:
        description: How do you find GitHub Actions?
        required: true
        type: choice
        options:
          - Awesome
          - Okay
          - Na

env:
  GREETING_WORD: Hello
  YOUR_NAME: ${{ inputs.yourName }}

jobs:
  Greeting:
    runs-on: ubuntu-latest
    env:
      GREETING_WORD: Good afternoon
    steps:
      - name: Say hello (step level env variables)
        env:
          GREETING_WORD: Good morning
        run: echo ${{ env.GREETING_WORD }}
      - name: Say hello (job level env variables)
        run: echo $GREETING_WORD
        if: ${{ env.GREETING_WORD == 'Good afternoon' }} 
      - name: Feeling good
        run: echo ${{ inputs.feelingGood }}
      - name: Print only if you are feeling good
        run: echo "Great! Have a nice workshop!"
        if: ${{ inputs.feelingGood == true }}
      - name: Print only if you are feeling bad
        run: echo "No worries! I'm here with you 😊"
        if: inputs.feelingGood == false
      - name: GitHub Actions is
        run: echo ${{ inputs.howYouFindGitHubActions }}
  Another_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello (workflow level env variables)
        run: echo ${{ env.GREETING_WORD }}
      - name: Dump github event context
        run: echo '${{ toJson(github.event) }}'
      - name: Dump runner context
        run: echo '${{ toJson(runner) }}'
