name: Demo calling resuable workflow

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/reusable-workflow.yml
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo Done!
